### ISSUE TITLE
leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-harbor-postgresql-stolon": the object has been modified; please apply your changes to the latest version and try again

### ISSUE THREAD

**Issue by koulq** [sorintlab/stolon#660] opened 2019-06-04 11:13 UTC
### Submission type

 - Bug report
 - Request for enhancement (RFE)

**Comment by sgotti** [comment] 2019-06-04 22:38
Duplicate of #582

@koulq Please provide all the needed info in the issue template (with the steps to reproduce the problem). Without such info it's quite impossible to understand what's happening

**Closed by sgotti** 2019-06-04 22:38 UTC

**Comment by nanjiyueguang** [comment] 2022-04-18 03:29
@koulq 
dear friend. 
I have the same problem ,cloud you tell me how you handled this issue?
