### ISSUE TITLE
Keeper doesn't get up after a liveness restart

### ISSUE THREAD

**Issue by guillelb** [sorintlab/stolon#437] opened 2018-02-12 12:02 UTC
A liveness probe detects that one keeper is not responding, and K8S restarts the container inside the Pod.

But when the container is booting, the log shows some errors like `keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}`

```
# kubectl logs -f stolon-keeper0-265045574-3bt6l
2018-02-12T11:43:07.770Z	WARN	keeper/keeper.go:164	password file permissions are too open. This file should only be readable to the user executing stolon! Continuing...	{"file": "/etc/secrets/stolon/password", "mode": "01000000777"}
2018-02-12T11:43:07.774Z	INFO	keeper/keeper.go:1672	exclusive lock on data dir taken
2018-02-12T11:43:07.775Z	INFO	keeper/keeper.go:442	keeper uid	{"uid": "keeper0"}
2018-02-12T11:43:07.793Z	INFO	postgresql/postgresql.go:264	stopping database
waiting for server to shut down............................................................... failed
pg_ctl: server does not shut down
2018-02-12T11:44:08.264Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T11:44:08.272Z	INFO	keeper/keeper.go:881	our db boot UID is different than the cluster data one, waiting for it to be updated	{"bootUUID": "fe3bb3b7-4bcc-49f5-bc54-21580221cbd4", "clusterBootUUID": "52b2b5f1-cf1f-4066-b6cb-37999c9a84c6"}
2018-02-12T11:44:08.273Z	INFO	postgresql/postgresql.go:264	stopping database
2018-02-12T11:44:10.873Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T11:44:13.390Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T11:44:15.905Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018
.
.
.
2018-02-12T11:34:27.081Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T11:34:29.664Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T11:34:29.677Z	INFO	keeper/keeper.go:1348	our db requested role is standby	{"followedDB": "4fce653e"}
2018-02-12T11:34:29.677Z	INFO	keeper/keeper.go:1367	already standby
2018-02-12T11:34:29.678Z	INFO	keeper/keeper.go:1489	postgres parameters not changed
2018-02-12T11:34:29.678Z	INFO	keeper/keeper.go:1498	postgres hba entries not changed
2018-02-12T11:34:32.188Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T11:34:34.768Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T11:34:34.779Z	INFO	keeper/keeper.go:1348	our db requested role is standby	{"followedDB": "4fce653e"}
2018-02-12T11:34:34.779Z	INFO	keeper/keeper.go:1367	already standby
2018-02-12T11:34:34.780Z	INFO	keeper/keeper.go:1489	postgres parameters not changed
2018-02-12T11:34:34.780Z	INFO	keeper/keeper.go:1498	postgres hba entries not changed
2018-02-12T11:34:35.923Z	INFO	postgresql/postgresql.go:264	stopping database
waiting for server to shut down.............
```

Only, when I kill the entire Pod, the boot process is correct, and keeper starts propperly:

```
# kubectl logs -f stolon-keeper0-265045574-rkhr2
2018-02-12T12:10:21.670Z	WARN	keeper/keeper.go:164	password file permissions are too open. This file should only be readable to the user executing stolon! Continuing...	{"file": "/etc/secrets/stolon/password", "mode": "01000000777"}
2018-02-12T12:10:21.674Z	INFO	keeper/keeper.go:1672	exclusive lock on data dir taken
2018-02-12T12:10:21.676Z	INFO	keeper/keeper.go:442	keeper uid	{"uid": "keeper0"}
2018-02-12T12:10:21.732Z	INFO	postgresql/postgresql.go:264	stopping database
pg_ctl: could not send stop signal (PID: 29): No such process
2018-02-12T12:10:21.757Z	INFO	keeper/keeper.go:881	our db boot UID is different than the cluster data one, waiting for it to be updated	{"bootUUID": "c04e7404-310a-4f5b-8db4-a221c95401cf", "clusterBootUUID": "4428a5fb-915f-4d19-87d1-4eb81779e9cd"}
2018-02-12T12:10:21.757Z	INFO	postgresql/postgresql.go:264	stopping database
2018-02-12T12:10:21.783Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:10:24.303Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:10:26.879Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:10:26.894Z	INFO	keeper/keeper.go:1348	our db requested role is standby	{"followedDB": "4fce653e"}
2018-02-12T12:10:26.894Z	INFO	keeper/keeper.go:1367	already standby
2018-02-12T12:10:26.939Z	INFO	postgresql/postgresql.go:241	starting database
pg_ctl: another server might be running; trying to start server anyway
waiting for server to start....LOG:  database system was interrupted while in recovery at log time 2018-02-12 07:42:31 UTC
HINT:  If this has occurred more than once some data might be corrupted and you might need to choose an earlier recovery target.
FATAL:  the database system is starting up
.FATAL:  the database system is starting up
2018-02-12T12:10:29.391Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "pq: the database system is starting up"}
.FATAL:  the database system is starting up
FATAL:  the database system is starting up
.FATAL:  the database system is starting up
.FATAL:  the database system is starting up
2018-02-12T12:10:31.917Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "pq: the database system is starting up"}
FATAL:  the database system is starting up
.LOG:  entering standby mode
LOG:  redo starts at 0/7482870
LOG:  consistent recovery state reached at 0/74A40C0
LOG:  database system is ready to accept read only connections
LOG:  invalid record length at 0/74A40C0: wanted 24, got 0
LOG:  started streaming WAL from primary at 0/7000000 on timeline 3
 done
server started
2018-02-12T12:10:33.005Z	INFO	keeper/keeper.go:1489	postgres parameters not changed
2018-02-12T12:10:33.005Z	INFO	keeper/keeper.go:1498	postgres hba entries not changed
2018-02-12T12:10:38.075Z	INFO	keeper/keeper.go:1348	our db requested role is standby	{"followedDB": "4fce653e"}
2018-02-12T12:10:38.075Z	INFO	keeper/keeper.go:1367	already standby
```

What is happening in this boot process?
Is there some difference between restart the Pod and restart the container?

Thank you in advance.

**Comment by sgotti** [comment] 2018-02-12 12:19
@guillelb from the logs I cannot understand what's the error you're reporting and the events (the timestamp aren't in order). Can you provide some detailed infos on where's the problem and how to reproduce it?

BTW why are you putting a liveness probe on the keeper? How are you probing the keeper? (what's the configuration of the probe?)

**Comment by guillelb** [comment] 2018-02-12 12:51
Hello,
The timestamp is not in order because the error is repeating, and I have copied and pasted from different sequences, but the content and the order is correct.

I use liveness probe because you recommended me that in the issue #354 :

_"I'm expecting that postgres will exit and if this isn't happening the check could be done externally using a script or inside k8s as a liveness probe "_


The liveness script is very symple, a `SELECT 1` query:


```
liveness-keeper.sh: |
    #!/bin/bash
    PGPASSWORD="xxxxx" /usr/lib/postgresql/9.6/bin/psql --host 127.0.0.1 --port 5432 postgres -U stolon -c "SELECT 1"
```


The problem only happen when the liveness probe fails, and K8S restart the container inside the Pod.
Keeper boots perfectly, when I delete manually the entire Pod not only the container.

**Comment by sgotti** [comment] 2018-02-12 14:45
@guillelb 

ok it's related to #354 so it's more clear.

1. Regarding your logs I can't see the part where the keeper start postgres at the start after the container has been restarted. Can you provide them?

The difference between killing a pod and restarting a container is that, in the latter the same local container root "volume" is kept (all process are killed). In this image we have under /tmp/ the previous postgresql socket file. From your logs looks like pg_ctl stop failed to stop postgres but postgres shouldn't running (since the container has been restarted). So looks like (due to storage errors?) the postgres process becomes blocked and not killable. But it'll be difficult or take time to reproduce here (On my env without storage problems restarting a container works correctly).

2. That liveness probe looks wrong. In #354 I meant to add a liveness probe on the storage status (to see if it's accessible) not on postgres. Since postgres is managed by the keeper (so it could start and stop it) the probe could trigger when the keeper has stopped postgres.

Are you using the latest version of stolon? (you ignored and dropped our issue template...)

**Comment by guillelb** [comment] 2018-02-12 15:36
The following is the entire log, from the restart until the next restart of the container:
```
2018-02-12T12:06:42.686Z	WARN	keeper/keeper.go:164	password file permissions are too open. This file should only be readable to the user executing stolon! Continuing...	{"file": "/etc/secrets/stolon/password", "mode": "01000000777"}
2018-02-12T12:06:42.690Z	INFO	keeper/keeper.go:1672	exclusive lock on data dir taken
2018-02-12T12:06:42.691Z	INFO	keeper/keeper.go:442	keeper uid	{"uid": "keeper0"}
2018-02-12T12:06:42.720Z	INFO	postgresql/postgresql.go:264	stopping database
pg_ctl: server does not shut down
waiting for server to shut down............................................................... failed
2018-02-12T12:07:43.092Z	INFO	keeper/keeper.go:881	our db boot UID is different than the cluster data one, waiting for it to be updated	{"bootUUID": "4428a5fb-915f-4d19-87d1-4eb81779e9cd", "clusterBootUUID": "855c4d4a-4eef-4bc5-bdf2-65080d9c9bd8"}
2018-02-12T12:07:43.092Z	INFO	postgresql/postgresql.go:264	stopping database
2018-02-12T12:07:43.121Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:07:45.635Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:07:48.166Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:07:50.686Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:07:53.278Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:07:55.873Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:07:58.482Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:08:01.001Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:08:03.574Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:08:06.091Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:08:08.674Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:08:11.273Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:08:13.872Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:08:16.386Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:08:18.974Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:08:21.489Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:08:24.066Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:08:26.584Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:08:29.102Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:08:31.615Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:08:34.173Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:08:36.688Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:08:39.201Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:08:41.730Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
pg_ctl: server does not shut down
waiting for server to shut down............................................................... failed
2018-02-12T12:08:44.249Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:08:46.772Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:08:48.630Z	INFO	keeper/keeper.go:1348	our db requested role is standby	{"followedDB": "4fce653e"}
2018-02-12T12:08:48.631Z	INFO	keeper/keeper.go:1367	already standby
2018-02-12T12:08:48.631Z	INFO	keeper/keeper.go:1484	postgres parameters changed, reloading postgres instance
2018-02-12T12:08:48.631Z	INFO	keeper/keeper.go:1498	postgres hba entries not changed
2018-02-12T12:08:48.631Z	INFO	postgresql/postgresql.go:298	reloading database configuration
server signaled
2018-02-12T12:08:49.275Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:08:51.885Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:08:53.733Z	INFO	keeper/keeper.go:1348	our db requested role is standby	{"followedDB": "4fce653e"}
2018-02-12T12:08:53.733Z	INFO	keeper/keeper.go:1367	already standby
2018-02-12T12:08:53.734Z	INFO	keeper/keeper.go:1489	postgres parameters not changed
2018-02-12T12:08:53.734Z	INFO	keeper/keeper.go:1498	postgres hba entries not changed
2018-02-12T12:08:54.465Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:08:56.993Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:08:58.826Z	INFO	keeper/keeper.go:1348	our db requested role is standby	{"followedDB": "4fce653e"}
2018-02-12T12:08:58.826Z	INFO	keeper/keeper.go:1367	already standby
2018-02-12T12:08:58.826Z	INFO	keeper/keeper.go:1489	postgres parameters not changed
2018-02-12T12:08:58.826Z	INFO	keeper/keeper.go:1498	postgres hba entries not changed
2018-02-12T12:08:59.495Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:09:02.017Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:09:03.889Z	INFO	keeper/keeper.go:1348	our db requested role is standby	{"followedDB": "4fce653e"}
2018-02-12T12:09:03.889Z	INFO	keeper/keeper.go:1367	already standby
2018-02-12T12:09:03.890Z	INFO	keeper/keeper.go:1489	postgres parameters not changed
2018-02-12T12:09:03.890Z	INFO	keeper/keeper.go:1498	postgres hba entries not changed
2018-02-12T12:09:04.519Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:09:07.039Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:09:09.006Z	INFO	keeper/keeper.go:1348	our db requested role is standby	{"followedDB": "4fce653e"}
2018-02-12T12:09:09.007Z	INFO	keeper/keeper.go:1367	already standby
2018-02-12T12:09:09.007Z	INFO	keeper/keeper.go:1489	postgres parameters not changed
2018-02-12T12:09:09.007Z	INFO	keeper/keeper.go:1498	postgres hba entries not changed
2018-02-12T12:09:09.541Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:09:12.092Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:09:14.109Z	INFO	keeper/keeper.go:1348	our db requested role is standby	{"followedDB": "4fce653e"}
2018-02-12T12:09:14.109Z	INFO	keeper/keeper.go:1367	already standby
2018-02-12T12:09:14.110Z	INFO	keeper/keeper.go:1489	postgres parameters not changed
2018-02-12T12:09:14.110Z	INFO	keeper/keeper.go:1498	postgres hba entries not changed
2018-02-12T12:09:14.594Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:09:17.111Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:09:19.192Z	INFO	keeper/keeper.go:1348	our db requested role is standby	{"followedDB": "4fce653e"}
2018-02-12T12:09:19.193Z	INFO	keeper/keeper.go:1367	already standby
2018-02-12T12:09:19.193Z	INFO	keeper/keeper.go:1489	postgres parameters not changed
2018-02-12T12:09:19.193Z	INFO	keeper/keeper.go:1498	postgres hba entries not changed
2018-02-12T12:09:19.614Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:09:22.133Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:09:24.291Z	INFO	keeper/keeper.go:1348	our db requested role is standby	{"followedDB": "4fce653e"}
2018-02-12T12:09:24.291Z	INFO	keeper/keeper.go:1367	already standby
2018-02-12T12:09:24.292Z	INFO	keeper/keeper.go:1489	postgres parameters not changed
2018-02-12T12:09:24.292Z	INFO	keeper/keeper.go:1498	postgres hba entries not changed
2018-02-12T12:09:24.636Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:09:27.156Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:09:29.394Z	INFO	keeper/keeper.go:1348	our db requested role is standby	{"followedDB": "4fce653e"}
2018-02-12T12:09:29.394Z	INFO	keeper/keeper.go:1367	already standby
2018-02-12T12:09:29.395Z	INFO	keeper/keeper.go:1489	postgres parameters not changed
2018-02-12T12:09:29.395Z	INFO	keeper/keeper.go:1498	postgres hba entries not changed
2018-02-12T12:09:29.658Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:09:32.176Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:09:34.494Z	INFO	keeper/keeper.go:1348	our db requested role is standby	{"followedDB": "4fce653e"}
2018-02-12T12:09:34.494Z	INFO	keeper/keeper.go:1367	already standby
2018-02-12T12:09:34.494Z	INFO	keeper/keeper.go:1489	postgres parameters not changed
2018-02-12T12:09:34.494Z	INFO	keeper/keeper.go:1498	postgres hba entries not changed
2018-02-12T12:09:34.682Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:09:37.285Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:09:39.592Z	INFO	keeper/keeper.go:1348	our db requested role is standby	{"followedDB": "4fce653e"}
2018-02-12T12:09:39.593Z	INFO	keeper/keeper.go:1367	already standby
2018-02-12T12:09:39.593Z	INFO	keeper/keeper.go:1489	postgres parameters not changed
2018-02-12T12:09:39.593Z	INFO	keeper/keeper.go:1498	postgres hba entries not changed
2018-02-12T12:09:39.787Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:09:42.380Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:09:44.694Z	INFO	keeper/keeper.go:1348	our db requested role is standby	{"followedDB": "4fce653e"}
2018-02-12T12:09:44.695Z	INFO	keeper/keeper.go:1367	already standby
2018-02-12T12:09:44.695Z	INFO	keeper/keeper.go:1489	postgres parameters not changed
2018-02-12T12:09:44.695Z	INFO	keeper/keeper.go:1498	postgres hba entries not changed
2018-02-12T12:09:44.964Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:09:47.485Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:09:49.795Z	INFO	keeper/keeper.go:1348	our db requested role is standby	{"followedDB": "4fce653e"}
2018-02-12T12:09:49.795Z	INFO	keeper/keeper.go:1367	already standby
2018-02-12T12:09:49.796Z	INFO	keeper/keeper.go:1489	postgres parameters not changed
2018-02-12T12:09:49.796Z	INFO	keeper/keeper.go:1498	postgres hba entries not changed
2018-02-12T12:09:49.987Z	ERROR	keeper/keeper.go:560	cannot get configured pg parameters	{"error": "dial unix /tmp/.s.PGSQL.5432: connect: no such file or directory"}
2018-02-12T12:09:50.890Z	INFO	postgresql/postgresql.go:264	stopping database
waiting for server to shut down.............
```

Software versions:
OS: Ubuntu 16.04
K8S: v1.7.11
Stolon keeper image:
```
REPOSITORY                                      TAG                 IMAGE ID            CREATED             SIZE
sorintlab/stolon                            master-pg9.6              5d6a0c1c2f42        4 months ago        399MB
```

Questions:
1. What liveness probe sholud I use? Can you show me an example?
2. Why do you think that it is an storage error? I have deployed a K8S infrastructure with 48 different Pods. No one of them never has showed something worng with the storage. How can we see it form sotolon?

**Comment by sgotti** [comment] 2018-02-13 12:26
> What liveness probe sholud I use? Can you show me an example?

IMHO you don't need any liveness probe. Since in #354 you were having strange problems due to glusterfs `Transport not connected` errors and for some strange reason postgres didn't exited due this errors I suggested to investigate and fix the issue. You should try to debug why it's happening since it's not normal. If you search the kubernetes issues on github there're different related to glusterfs (or you can open a new one if there's not something like your issue already opened).

If you insist to use a liveness probe I'll consider that as a workaround and not a real fix. If so you can create a probe that tries to read/write a file from the storage and if this read/write returns an error then fail the probe.


> Why do you think that it is an storage error? I have deployed a K8S infrastructure with 48 different Pods. No one of them never has showed something worng with the storage. How can we see it from stolon?

Am I wrong or all of this started from the glusterfs errors reported in #354?

From the logs I can see that the probe made the container restart but the new keeper process  (executing `pg_ctl stop`) isn't able to stop the instance. But the instance shouldn't really be active due to the container being restarted (all the processes should have been killed). If this isn't happening then there's something wrong. You should try to understand what's happening. This isn't happening on our environments so you should try to debug what's really happening.

On the keeper side we can improve the stop logic to not continue when the stop fails but this won't fix the problem, just avoid to continue if stop fails (will open a PR)

**Comment by sgotti** [comment] 2018-02-23 10:37
@guillelb I'm going to close this since I can't see a bug in stolon but it looks related to your environment. If you have more questions please continue the discussion on gitter or the mailing list.

**Closed by sgotti** 2018-02-23 10:37 UTC
