### ISSUE TITLE
cannot get sentinels info: unexpected end of JSON input

### ISSUE THREAD

**Issue by nh2** [sorintlab/stolon#396] opened 2017-12-30 03:08 UTC
### Submission type

 - Bug report

### Environment

On a system that's under heavy load, I sometimes get

```
# stolonctl status --cluster-name mycluster --store-backend=consul
cannot get sentinels info: unexpected end of JSON input
```

Looking at `consul kv get -recurse`, I see

```
...
stolon/cluster/mycluster/sentinel-leader:4f490a5e
stolon/cluster/mycluster/sentinels/info/2240a711:
stolon/cluster/mycluster/sentinels/info/4f490a5e:{"UID":"4f490a5e"}
stolon/cluster/mycluster/sentinels/info/871d0773:{"UID":"871d0773"}
```

Shouldn't there be some JSON after the `2240a711:`? Is stolon's state corrupted here?

Similarly, I right now get

```
# stolonctl status --cluster-name mycluster --store-backend=consul
=== Active sentinels ===

ID		LEADER
4f490a5e	true
cannot get proxies info: unexpected end of JSON input
```

with the KV store containing

```
...
stolon/cluster/benaco-stolon-cluster/proxies/info/9fd707d7:{"UID":"9fd707d7","Generation":276}
stolon/cluster/benaco-stolon-cluster/proxies/info/da5fd3f9:
stolon/cluster/benaco-stolon-cluster/sentinel-leader:4f490a5e
stolon/cluster/benaco-stolon-cluster/sentinels/info/4f490a5e:{"UID":"4f490a5e"}
```

In this case, there seems to be missing JSON behind the proxy entry `da5fd3f9:`.

**Comment by sgotti** [comment] 2017-12-30 09:31
@nh2 Looks like consul returns keys with an empty value. We're just doing a simple put (not atomic) using libkv to consul so looks like consul KV store is behaving badly, it should report all or nothing. Is this reproducible only under consul high load?

**Comment by sgotti** [comment] 2017-12-30 10:33
@nh2 These keys are written using a TTL to expire them after some seconds. Perhaps under load consul isn't handling TTL correctly removing only the value and leaving the key with an empty value? BTW these aren't big issues, it'll be really bad if this happened with the cluster data and not so good if happening with sentinel leader election.

**Comment by sgotti** [comment] 2018-02-23 10:38
@nh2 I'm going to close this since it lookd like a really bad consul behavior and we can't do nothing.

**Closed by sgotti** 2018-02-23 10:38 UTC
