### ISSUE TITLE
Promote Slave DB into master when Master DB fails or network is split

### ISSUE THREAD

**Issue by kimss** [sorintlab/stolon#331] opened 2017-08-01 13:39 UTC
Hi Sorintlab,
please consider the enhancement:

In two-node cluster it makes sense to promote the slave DB to master when the master disappears in case the available ETCD node is in quorum state.

**Comment by sgotti** [comment] 2017-08-02 08:12
@kimss Sorry but I don't understand your request. Looks like you're asking for a basic stolon feature that is already implemented: f the etcd cluster is working and if a keeper cannot talk with etcd (but the other keeper can), the sentinel (if it can talk with etcd) will declare that node as dead and promote (if it can be elected) the other node as master.

Can you provide more details on how you're implementing your stolon cluster and what you noticed vs what you were expecting, the logs and the steps to reproduce it?

**Comment by kimss** [comment] 2017-08-04 12:31
@sgotti 
Here is a detailed explanation:
------------------------------------------
Let's say we have an environment:
1) Server A: 
- ETCD
2) Server B:
- ETCD
- Stolon + Master DB
3) Server C
- ETCD
- Stolon + Slave DB (synchronous)

Scenario:
- Server B is network separated from the servers A & C.
--------------------------------------------
Action:
- Promote DB on server C into Master DB and redirect DB client to this database.
Would it be possible?

**Comment by sgotti** [comment] 2017-08-08 07:01
@kimss In this scenario the db on server C is promoted as master, it's just that with sync repl it won't commit transaction since there's no available sync standby. So looks you're asking for the same thing as #330.

I'm going to close this in favor of #330. If you don't see this behavior (covered by the integration tests) please provide the keepers and master sentinel logs.

**Closed by sgotti** 2017-08-08 07:01 UTC

**Comment by kimss** [comment] 2017-08-08 09:21
@sgotti 
Yes, we observe that sync slave into master when the PostgreSQL/Keeper dies. And it is OK.

But is our case the whole Server is separated from A & C (by network split). In this case the promotion not happens. Should it happen or not? Obviously in this case the Sentinel on Server C cannot "see" the Sentinel on Server B

**Comment by sgotti** [comment] 2017-08-08 09:32
@kimss sorry but I don't completely understand your explanation. If the steps are the ones provided here (https://github.com/sorintlab/stolon/issues/331#issuecomment-320236855) then promotion will happen if the standby db on server C is synced and can talk with a quorate etcd. If it's not elected there will be something else preventing this. Can you provide the related sentinel and keeper logs (to debug level)?

> Obviously in this case the Sentinel on Server C cannot "see" the Sentinel on Server B

If a leader sentinel cannot talk with etcd it'll lose its leader "lock" and a new election will happen (all the stolon component talks only with etcd, there's no direct communication between them).

**Comment by kimss** [comment] 2017-08-09 11:24
@sgotti 
It looks strange but I'm failing to reproduce the issue in the cluster with 2 DB nodes. Though it was a stable case until the "git pull" today.
Now I see the slave DB is promoted into Master on the stable basis if the Master DB is network separated (its ECTD instance lost quorum). 
Have you implemented any critical fixes within the past week?

**Comment by sgotti** [comment] 2017-08-09 11:30
> Have you implemented any critical fixes within the past week?

@kimss I don't think so, this is a very basic feature the is the core of stolon and covered by the integration tests.

I think that there was something else broken (for example the standby wasn't in sync and won't be elected as master like reported in your mail of today: https://groups.google.com/forum/#!topic/stolon/YK33RI6tE1g)

**Comment by kimss** [comment] 2017-08-09 11:39
@sgotti 
Ok, now I see that the parameters PGWANTEDGENERATION/PGCURRENTGENERATION should be consistent to each other somehow. Are there any descriptions of the mentioned parameters?

Also, I have a question regarding https://github.com/sorintlab/stolon/issues/330. Is it possible to implement automatic deactivation of synchronous replication in case the slave is promoted into master or the synchronous slave disappeared in the environment that consists of 2 nodes? It seems that enabling of synchronous replication can be an automatic option which is performed when "synchronousReplication" is true and at least 1 async slave DB is available.

Thank you!
