### ISSUE TITLE
Cluster stops working in case of proxy death

### ISSUE THREAD

**Issue by sergik** [sorintlab/stolon#481] opened 2018-04-27 15:08 UTC
### Submission type

 - Bug report

### Environment
kubernetes 1.9
#### Stolon version
v0.10.0-pg9.6
### Expected behaviour you didn't see
Cluster does not stop works in case proxy stops working unexpectedly.
### Unexpected behaviour you saw
We have stolon cluster installation in kubernetes. 3 keepers. 2 sentinels. 2 proxies. Consul as backend. Periodically we got following error which stops cluster work until manual fix. In sentinel log we have the following:
```
2018-04-27T14:28:14.082Z        ERROR   sentinel/sentinel.go:1613       failed to get proxies info      {"error": "unexpected end of JSON input"}
2018-04-27T14:28:19.171Z        ERROR   sentinel/sentinel.go:1613       failed to get proxies info      {"error": "unexpected end of JSON input"}
2018-04-27T14:28:24.270Z        ERROR   sentinel/sentinel.go:1613       failed to get proxies info      {"error": "unexpected end of JSON input"}
2018-04-27T14:28:29.472Z        INFO    sentinel/sentinel.go:1045       waiting for proxies to close connections to old master
2018-04-27T14:28:34.670Z        INFO    sentinel/sentinel.go:1045       waiting for proxies to close connections to old master
2018-04-27T14:28:39.771Z        INFO    sentinel/sentinel.go:1045       waiting for proxies to close connections to old master
2018-04-27T14:28:44.796Z        INFO    sentinel/sentinel.go:1045       waiting for proxies to close connections to old master
2018-04-27T14:28:50.072Z        INFO    sentinel/sentinel.go:1045       waiting for proxies to close connections to old master
2018-04-27T14:28:55.182Z        INFO    sentinel/sentinel.go:1045       waiting for proxies to close connections to old master
2018-04-27T14:29:00.476Z        INFO    sentinel/sentinel.go:1045       waiting for proxies to close connections to old master
2018-04-27T14:29:05.670Z        INFO    sentinel/sentinel.go:1045       waiting for proxies to close connections to old master
2018-04-27T14:29:10.784Z        INFO    sentinel/sentinel.go:1045       waiting for proxies to close connections to old master
2018-04-27T14:29:15.971Z        INFO    sentinel/sentinel.go:1045       waiting for proxies to close connections to old master
2018-04-27T14:29:21.170Z        INFO    sentinel/sentinel.go:1045       waiting for proxies to close connections to old master
2018-04-27T14:29:26.470Z        INFO    sentinel/sentinel.go:1045       waiting for proxies to close connections to old master
2018-04-27T14:29:31.572Z        INFO    sentinel/sentinel.go:1045       waiting for proxies to close connections to old master
2018-04-27T14:29:36.599Z        INFO    sentinel/sentinel.go:1045       waiting for proxies to close connections to old master
2018-04-27T14:29:41.682Z        INFO    sentinel/sentinel.go:1045       waiting for proxies to close connections to old master
```
In cluster config in consul there are 3 proxies record(we have only 2 proxies). Third record stays forever and sentinel thinks that there is proxy which did not close connection to old master. But this proxy already dead. I look into the code and found that proxy writes this keys with TTL and it should disapear in some period(30 sec) but looks like for some reason it does not happen.
Previously we used etcd and didn't face this behavior. 
### Steps to reproduce the problem
Happens few times a day. Could not find straight steps to reproduce.

**Comment by sgotti** [comment] 2018-04-27 15:44
@sergik this is like #397. If you take a look at the debugging in the comments looks like this is a bad consul bug that doesn't correctly expires keys. I'm not sure since it's really difficult to reproduce. My suggestion until this isn't reproducible is to use the etcdv3 store.

**Comment by sgotti** [comment] 2018-06-05 12:23
@sergik I'm going to close this as duplicated of #397. Ask to reopen if you have more information and think it's not related to that issue.

**Closed by sgotti** 2018-06-05 12:23 UTC
