### ISSUE TITLE
Cannot connect to Keeper's Postgres instance

### ISSUE THREAD

**Issue by jiri463** [sorintlab/stolon#135] opened 2016-04-14 14:31 UTC
Hi,

I am trying to run your Kubernetes example.

I was able to achieve to run all pods/services, but when I tried to connect to proxy service (command psql --host my_ip --port 5432 postgres -U stolon -W ), it failed. So I "connect" to running stolon-keeper Docker container and tried to connect to Postgres instance by command: psql --host localhost --port 5432 postgres -U stolon -W . After password is written the error occurs:

> psql: could not connect to server: Connection refused
>         Is the server running on host "localhost" (::1) and accepting
>         TCP/IP connections on port 5432?
> could not connect to server: Connection refused
>         Is the server running on host "localhost" (127.0.0.1) and accepting
>         TCP/IP connections on port 5432?

So, I listed keeper's log:

![stolon1](https://cloud.githubusercontent.com/assets/18463872/14531407/82023bd0-025d-11e6-828d-09192d89646b.png)

And there is written that postgresql was stoped (time 14:27:13090). Any suggestions what is wrong?

Note: I followed kubernetes example step by step. Only for topic: Setup Superuser password, I did not know what should I do exactly. Thanks.

**Comment by sgotti** [comment] 2016-04-14 15:36
Looks like the clusterview is not populated by the sentinel due to various reasons (problems connecting to etcd, discovering keepers etc...).

Can you provide the sentinels and keepers logs in a gist or remote location (possibly in textual form using `kubectl logs` since it becomes difficult to read a reverse time ordered image).

**Comment by jiri463** [comment] 2016-04-19 18:04
It seems that it is problem with etcd. But when I run command from let say stolon keeper docker container:

> curl -L -X GET http://etcd-client:2379/v2/keys

it returns 

> {"action":"get","node":{"dir":true,"nodes":[{"key":"/stolon","dir":true,"modifiedIndex":8,"createdIndex":8}]}}

So it seems that etcd is working.

Below are my logs (Sorry for print screen, but I have no other option actually)

keeper

![keper](https://cloud.githubusercontent.com/assets/18463872/14649912/7ba420b8-0669-11e6-8f3e-e589d370eb70.png)

sentinel

![sentinel](https://cloud.githubusercontent.com/assets/18463872/14649920/835748ee-0669-11e6-8014-2ae1cb40f167.png)

proxy

![proxy](https://cloud.githubusercontent.com/assets/18463872/14649928/8aabc520-0669-11e6-9d6b-a9132a7d4e8a.png)

In stolon-keeper.yaml I have:

>         env:
>           - name: KEEPER
>             value: "true"
>           - name: STKEEPER_CLUSTER_NAME
>           # TODO(sgotti) Get cluster name from "stoloncluster" label using a downward volume api instead of duplicating the name here
>             value: "kube-stolon"
>           - name: STKEEPER_STORE_BACKEND
>             value: "etcd" # Or consul
>           - name: STKEEPER_STORE_ENDPOINTS
>             value: "etcd-client:2379"

Why is database turn of when stolon dos not work correctly? Thank you very much

**Comment by jiri463** [comment] 2016-04-20 07:37
Etcd version: {"etcdserver":"2.3.1","etcdcluster":"2.3.0"}

**Comment by jiri463** [comment] 2016-04-25 09:22
Any ideas? Thanks.

**Comment by sgotti** [comment] 2016-04-26 14:32
@jiri463 The problem is in the sentinel's line `err: failed to get running pods ips: cannot retrieve kube ca certificate [...]`. This means that it cannot initialize the cluster view since it cannot discover the running stolon keepers.

Looks like your kubernetes cluster doesn't have a apiservice certificate configured (with the apiserver options `--cert-dir` or `,--tls-cert-file`) or https serving is disabled.
Actually stolon need https serving enabled and a ca file to verify the server identity. Perhaps an options should be added to disable this check (actually all the tested kubernetes clusters have https enabled and the certificate are provided).

Can you provide some more information on how your kubernetes cluster is configured?

> Why is database turn of when stolon dos not work correctly?

The keeper is the manager of the postgres instance. It won't be able to know how to execute the postgres (which role?) instance if it doesn't know the required cluster information (like its role, the cluster configuration  etc...). In your case the sentinel isn't initializing the cluster due to the above problem.

**Comment by jiri463** [comment] 2016-04-28 13:48
Thank you for reply. 

> Looks like your kubernetes cluster doesn't have a apiservice certificate configured 

You are absolutely right, we have not certificated kubernetes apiservice for now. We must change it now. 

> Perhaps an options should be added to disable this check

Some switch would be nice. 

> The keeper is the manager of the postgres instance. It won't be able to know how to execute the postgres (which role?) instance if it doesn't know the required cluster information (like its role, the cluster configuration etc...). In your case the sentinel isn't initializing the cluster due to the above problem.

Thanks for answer. It makes me sense.

**Comment by jiri463** [comment] 2016-05-05 16:57
It is still failing for us.

Our cluster should support certificated apiservice now. Although, Postgres instance is started and it is alive when keeper is running so I can connect to it from keeper container (so there is progress since last problem). But when I want to connect to it via service ip, request fails. I found error message in sentinel's logs:

>  failed to update cluster View: cannot choose initial master, no keepers registered.

It is obvious why I cannot connect via service ip when keepers are not registered, but I have no clue why they are not registered.  Any idea? Thank you.

Below are logs of all stolon components.
[keper-logs.txt](https://github.com/sorintlab/stolon/files/250776/keper-logs.txt)
[proxy-logs.txt](https://github.com/sorintlab/stolon/files/250777/proxy-logs.txt)
[sentinel-logs.txt](https://github.com/sorintlab/stolon/files/250779/sentinel-logs.txt)

**Comment by sgotti** [comment] 2016-05-05 21:12
> It is obvious why I cannot connect via service ip when keepers are not registered, but I have no clue why they are not registered. Any idea? Thank you.

Now looks like api calls are working but no keeper pods are returned. Are you using a different k8s namespace than "default" or any other change to the examples replication controllers yaml (like labels)?


#129 adds an options to define the discovery type. In this way you can disable kubernetes based discovery type and use the store based discovery.

**Comment by jiri463** [comment] 2016-05-06 18:14
> Are you using a different k8s namespace than "default" or any other change to the examples replication controllers yaml (like labels)?

Yes, I did. I use namespace "stolon" and add one label.

 I found out that there is env property "STSENTINEL_KUBERNETES_NAMESPACE" which is set to "default". So I changed it to "stolon". But it stil do no work, but there little progress. It seems that keeper is found but still I cannot connect to it via stolon-proxy service (connection timeout). 

I looked into logs and there is written:

> proxy: master address: 10.244.92.4:5432

So I tried to connect via this ip and it is working. So there is my progress :)

But there are also logs which I do not understand: 
> 
proxy: proxyInfo: (*cluster.ProxyInfo){ID:(string)8b1eab8a ListenAddress:(string)172.17.0.4 Port:(string)5432 ClusterViewVersion:(int)3}

I tried to deploy stolon into Kubernetes few times and one time I was able to connect to keeper's Postgres instance via ip 172.17.0.4, which I do not absolutely understand because it is not a Kubernetes virtual ip, because it does not starts by 10 and I was able to reproduce it only one time.

Actual logs are below:
[keeper-logs.txt](https://github.com/sorintlab/stolon/files/252786/keeper-logs.txt)
[proxy-logs.txt](https://github.com/sorintlab/stolon/files/252787/proxy-logs.txt)
[sentinel-logs.txt](https://github.com/sorintlab/stolon/files/252789/sentinel-logs.txt)


> #129 adds an options to define the discovery type. In this way you can disable kubernetes based discovery type and use the store based discovery.

I have two questions. The first is, how can I setup discovery type? It is enough to add environment properties into all controllers yaml files (Sorry that I am asking but I had no time to try it today)?  Something like: 

```
- name: STSENTINEL_DISCOVERY-TYPE
            value: "store"    # or "kubernetes"
```

The second question is, what are pros & cos to use kubernetes or store (eg. etcd) discovery type? 

Thanks a lot

**Comment by sgotti** [comment] 2016-11-24 11:04
In the current master a lot of changes have been done to stolon. The discovery type has been removed and now everything is done using the store. I hope this will remove a lot of confusion. So I'm closing this. Please open any issue against the current master if you're going to try it.

**Closed by sgotti** 2016-11-24 11:04 UTC
