### ISSUE TITLE
Hope to support the zookeeper component

### ISSUE THREAD

**Issue by jackin853** [sorintlab/stolon#871] opened 2022-04-01 08:22 UTC
**Hope to support the zookeeper component**:

**At present, our entire kubernetes cluster already contains a zookeeper cluster, and we do not want to use the underlying etcd and configmap (this is maintained by another department), and the use of etcd and configmap often has the problem of connection timeout. If additional consul-like components are introduced, it will Increase the cost of maintenance, so is there a plan to support zookeeper?**

**Comment by sgotti** [comment] 2022-04-01 10:31
Duplicate of #542

**Closed by sgotti** 2022-04-01 10:31 UTC
Labels: enhancement
