### ISSUE TITLE
Cluster stops working after turn off/on all nodes with kube api as store.

### ISSUE THREAD

**Issue by sergik** [sorintlab/stolon#483] opened 2018-05-02 09:07 UTC
### Submission type

 - Bug report

### Environment
kube 1.9
#### Stolon version
latest master tag

When we faced problems with consul https://github.com/sorintlab/stolon/issues/481 we tried use built in kube api store. We turn off all our staging clusters every night. After turning cluster on we see the following error in sentinel logs and cluster stop working:

```
2018-05-02T08:00:28.961Z        WARN    cmd/sentinel.go:284     received db state for unexpected db uid {"receivedDB": "ce6c8ee4", "db": "b5c554c0", "keeper": "172_31_57_131"}
ERROR: logging before flag.Parse: E0502 08:08:11.439356       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E0502 08:13:46.544019       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E0502 08:16:16.744933       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E0502 08:17:31.742832       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E0502 08:19:15.737739       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E0502 08:20:21.636399       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E0502 08:21:05.931526       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E0502 08:21:43.135397       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
```

### Expected behaviour you didn't see
Stolon works correctly in case of cluster restart.
### Unexpected behaviour you saw
Stolon crashes after turn off/on all cluster nodes.
### Steps to reproduce the problem
1. Use kube api as store
2. Turn off/on all cluster nodes.

**Comment by sgotti** [comment] 2018-05-02 15:02
@sergik We can stop and start a k8s cluster without any issue. That messages comes from the k8s client leaderelection code and will be normal if it happens some times due to how the election works but should be harmful.

Additionally from the first log entry you posted `2018-05-02T08:00:28.961Z        WARN    cmd/sentinel.go:284     received db state for unexpected db uid {"receivedDB": "ce6c8ee4", "db": "b5c554c0", "keeper": "172_31_57_131"}` I see that the sentinel is a leader (or that message won't be logged).

So can you check that the stolon cluster is really not working and if so provide more logs from all the sentinels and keepers and stolonctl status output because it could not be related to the logs you posted.

**Comment by sergik** [comment] 2018-05-03 08:28
Started stoped cluster. It stoped working. Here is output from the all roles. 
We have 3 keepers. 2 propxies and 2 sentinels. Here are their logs:
Keeper 1:
```
2018-05-03T08:20:14.754Z        INFO    cmd/keeper.go:1464      already master
2018-05-03T08:20:14.844Z        INFO    cmd/keeper.go:1628      postgres parameters not changed
2018-05-03T08:20:14.844Z        INFO    cmd/keeper.go:1639      postgres hba entries not changed
2018-05-03T08:20:19.863Z        INFO    cmd/keeper.go:1436      our db requested role is master
2018-05-03T08:20:19.943Z        INFO    cmd/keeper.go:1464      already master
2018-05-03T08:20:19.953Z        INFO    cmd/keeper.go:1628      postgres parameters not changed
2018-05-03T08:20:19.954Z        INFO    cmd/keeper.go:1639      postgres hba entries not changed
```
Keeper 2:
```
2018-05-03T08:21:44.835Z        INFO    cmd/keeper.go:1497      already standby
2018-05-03T08:21:44.845Z        INFO    cmd/keeper.go:1628      postgres parameters not changed
2018-05-03T08:21:44.845Z        INFO    cmd/keeper.go:1639      postgres hba entries not changed
2018-05-03T08:21:49.930Z        INFO    cmd/keeper.go:1478      our db requested role is standby        {"followedDB": "1fae0254"}
2018-05-03T08:21:49.930Z        INFO    cmd/keeper.go:1497      already standby
2018-05-03T08:21:49.942Z        INFO    cmd/keeper.go:1628      postgres parameters not changed
2018-05-03T08:21:49.942Z        INFO    cmd/keeper.go:1639      postgres hba entries not changed
2018-05-03T08:21:55.030Z        INFO    cmd/keeper.go:1478      our db requested role is standby        {"followedDB": "1fae0254"}
2018-05-03T08:21:55.030Z        INFO    cmd/keeper.go:1497      already standby
2018-05-03T08:21:55.041Z        INFO    cmd/keeper.go:1628      postgres parameters not changed
2018-05-03T08:21:55.041Z        INFO    cmd/keeper.go:1639      postgres hba entries not changed
```

Keeper 3:
```
2018-05-03T08:22:34.229Z        INFO    cmd/keeper.go:1497      already standby
2018-05-03T08:22:34.246Z        INFO    cmd/keeper.go:1628      postgres parameters not changed
2018-05-03T08:22:34.247Z        INFO    cmd/keeper.go:1639      postgres hba entries not changed
2018-05-03T08:22:39.432Z        INFO    cmd/keeper.go:1478      our db requested role is standby        {"followedDB": "1fae0254"}
2018-05-03T08:22:39.432Z        INFO    cmd/keeper.go:1497      already standby
2018-05-03T08:22:39.442Z        INFO    cmd/keeper.go:1628      postgres parameters not changed
2018-05-03T08:22:39.442Z        INFO    cmd/keeper.go:1639      postgres hba entries not changed

```

Sentinel 1:

```
2018-05-03T07:47:59.667Z        INFO    cmd/sentinel.go:1903    sentinel uid    {"uid": "85edb885"}
2018-05-03T07:48:00.448Z        INFO    cmd/sentinel.go:96      Trying to acquire sentinels leadership
ERROR: logging before flag.Parse: I0503 07:48:00.646386       1 leaderelection.go:174] attempting to acquire leader lease...
ERROR: logging before flag.Parse: E0503 08:15:53.653944       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: I0503 08:18:34.442489       1 leaderelection.go:184] successfully acquired lease postgres/stolon-cluster-postgres
2018-05-03T08:18:34.644Z        INFO    cmd/sentinel.go:103     sentinel leadership acquired
ERROR: logging before flag.Parse: E0503 08:20:05.853366       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E0503 08:21:26.242408       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
```

Sentinel 2:
```
2018-05-03T07:47:59.667Z        INFO    cmd/sentinel.go:1903    sentinel uid    {"uid": "85edb885"}
2018-05-03T07:48:00.448Z        INFO    cmd/sentinel.go:96      Trying to acquire sentinels leadership
ERROR: logging before flag.Parse: I0503 07:48:00.646386       1 leaderelection.go:174] attempting to acquire leader lease...
ERROR: logging before flag.Parse: E0503 08:15:53.653944       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: I0503 08:18:34.442489       1 leaderelection.go:184] successfully acquired lease postgres/stolon-cluster-postgres
2018-05-03T08:18:34.644Z        INFO    cmd/sentinel.go:103     sentinel leadership acquired
ERROR: logging before flag.Parse: E0503 08:20:05.853366       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E0503 08:21:26.242408       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
root@ip-172-31-57-131:~# kubectl logs stolon-sentinel-7854cdcb6b-w2jqr -n postgres
2018-05-03T07:47:23.346Z        INFO    cmd/sentinel.go:1903    sentinel uid    {"uid": "4748eb48"}
2018-05-03T07:47:24.129Z        INFO    cmd/sentinel.go:96      Trying to acquire sentinels leadership
ERROR: logging before flag.Parse: I0503 07:47:24.236933       1 leaderelection.go:174] attempting to acquire leader lease...
ERROR: logging before flag.Parse: I0503 07:47:46.693273       1 leaderelection.go:184] successfully acquired lease postgres/stolon-cluster-postgres
2018-05-03T07:47:46.855Z        INFO    cmd/sentinel.go:103     sentinel leadership acquired
ERROR: logging before flag.Parse: E0503 07:48:36.331250       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E0503 07:49:10.344946       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E0503 07:49:35.838047       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E0503 07:50:32.739142       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E0503 07:51:43.327309       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E0503 07:53:13.829593       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E0503 07:54:54.840215       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E0503 07:58:09.335391       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E0503 07:59:48.429434       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E0503 08:01:31.436149       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E0503 08:03:22.529789       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E0503 08:07:21.342559       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E0503 08:12:30.443208       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E0503 08:15:41.941686       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E0503 08:18:26.840829       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E0503 08:18:45.645482       1 leaderelection.go:258] Failed to update lock: Operation cannot be fulfilled on configmaps "stolon-cluster-postgres": the object has been modified; please apply your changes to the latest version and try again
ERROR: logging before flag.Parse: E0503 08:18:46.337131       1 event.go:260] Could not construct reference to: '&v1.ConfigMap{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"", GenerateName:"", Namespace:"", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, Data:map[string]string(nil)}' due to: 'selfLink was empty, can't make reference'. Will not report event: 'Normal' 'LeaderElection' '4748eb48 stopped leading'
ERROR: logging before flag.Parse: I0503 08:18:48.132528       1 leaderelection.go:203] failed to renew lease postgres/stolon-cluster-postgres: timed out waiting for the condition
2018-05-03T08:18:48.530Z        INFO    cmd/sentinel.go:108     sentinel leadership lost
ERROR: logging before flag.Parse: I0503 08:18:49.533741       1 leaderelection.go:174] attempting to acquire leader lease...
```

Proxy 1:

```
2018-05-03T08:25:14.747Z        INFO    cmd/proxy.go:132        Starting proxying
2018-05-03T08:25:18.743Z        INFO    cmd/proxy.go:251        master address  {"address": "172.16.2.41:5432"}
2018-05-03T08:25:20.345Z        INFO    cmd/proxy.go:279        check timeout timer fired
2018-05-03T08:25:21.342Z        INFO    cmd/proxy.go:166        Stopping listening
2018-05-03T08:25:32.051Z        INFO    cmd/proxy.go:263        proxying to master address      {"address": "172.16.2.41:5432"}
2018-05-03T08:25:41.342Z        INFO    cmd/proxy.go:132        Starting proxying
2018-05-03T08:25:44.144Z        INFO    cmd/proxy.go:251        master address  {"address": "172.16.2.41:5432"}
2018-05-03T08:25:47.542Z        INFO    cmd/proxy.go:279        check timeout timer fired
2018-05-03T08:25:48.348Z        INFO    cmd/proxy.go:166        Stopping listening
2018-05-03T08:25:53.051Z        INFO    cmd/proxy.go:263        proxying to master address      {"address": "172.16.2.41:5432"}
2018-05-03T08:26:02.559Z        INFO    cmd/proxy.go:132        Starting proxying
2018-05-03T08:26:05.943Z        INFO    cmd/proxy.go:251        master address  {"address": "172.16.2.41:5432"}
2018-05-03T08:26:08.442Z        INFO    cmd/proxy.go:279        check timeout timer fired
2018-05-03T08:26:09.246Z        INFO    cmd/proxy.go:166        Stopping listening
2018-05-03T08:26:14.357Z        INFO    cmd/proxy.go:263        proxying to master address      {"address": "172.16.2.41:5432"}
2018-05-03T08:26:23.652Z        INFO    cmd/proxy.go:132        Starting proxying
2018-05-03T08:26:27.049Z        INFO    cmd/proxy.go:251        master address  {"address": "172.16.2.41:5432"}
2018-05-03T08:26:29.747Z        INFO    cmd/proxy.go:279        check timeout timer fired
2018-05-03T08:26:30.642Z        INFO    cmd/proxy.go:166        Stopping listening
2018-05-03T08:26:41.458Z        INFO    cmd/proxy.go:263        proxying to master address      {"address": "172.16.2.41:5432"}
```

Proxy 2:

```
2018-05-03T08:26:30.734Z        INFO    cmd/proxy.go:166        Stopping listening
2018-05-03T08:26:34.340Z        INFO    cmd/proxy.go:263        proxying to master address      {"address": "172.16.2.41:5432"}
2018-05-03T08:26:43.230Z        INFO    cmd/proxy.go:132        Starting proxying
2018-05-03T08:26:46.931Z        INFO    cmd/proxy.go:251        master address  {"address": "172.16.2.41:5432"}
2018-05-03T08:26:49.729Z        INFO    cmd/proxy.go:279        check timeout timer fired
2018-05-03T08:26:50.027Z        INFO    cmd/proxy.go:166        Stopping listening
2018-05-03T08:26:54.836Z        INFO    cmd/proxy.go:263        proxying to master address      {"address": "172.16.2.41:5432"}
2018-05-03T08:27:05.935Z        INFO    cmd/proxy.go:132        Starting proxying
2018-05-03T08:27:08.933Z        INFO    cmd/proxy.go:251        master address  {"address": "172.16.2.41:5432"}
2018-05-03T08:27:10.228Z        INFO    cmd/proxy.go:279        check timeout timer fired
2018-05-03T08:27:10.934Z        INFO    cmd/proxy.go:166        Stopping listening
2018-05-03T08:27:21.927Z        INFO    cmd/proxy.go:263        proxying to master address      {"address": "172.16.2.41:5432"}
```

**Comment by sgotti** [comment] 2018-05-03 10:06
@sergik From the logs I see that the keepers and sentinels are correcly running. The problem is in the proxyes that timeouts, probably talking with the store that the error isn't reported. My supposition is that they're timing somewhere (talking with the API, resolving addresses calling kube-dns or something else). 

Can you provide the `stolonctl clusterdata` output and take a stack dump of a proxy (sending a SIGQUIT to the proxy process). For example:

```
kubectl exec -it stolon-proxy-577f4f8494-8ck7h -- killall -QUIT stolon-proxy
kubectl logs -f --previous po/stolon-proxy-577f4f8494-8ck7h
```

**Comment by sergik** [comment] 2018-05-03 13:59
Cluster data:
`{"formatVersion":1,"changeTime":"2018-05-03T13:37:31.635044084Z","cluster":{"uid":"5c41c64c","generation":1,"changeTime":"2018-05-03T09:22:23.407103595Z","spec":{"additionalWalSenders":null,"additionalMasterReplicationSlots":null,"initMode":"existing","existingConfig":{"keeperUID":"172_31_222_81"},"pgParameters":{"datestyle":"iso, mdy","default_text_search_config":"pg_catalog.english","dynamic_shared_memory_type":"posix","lc_messages":"en_US.utf8","lc_monetary":"en_US.utf8","lc_numeric":"en_US.utf8","lc_time":"en_US.utf8","log_timezone":"UTC","max_connections":"100","shared_buffers":"128MB","timezone":"UTC","wal_level":"replica"},"pgHBA":null},"status":{"phase":"normal","master":"5a363897"}},"keepers":{"172_31_176_43":{"uid":"172_31_176_43","generation":1,"changeTime":"2018-05-03T13:37:38.030068117Z","spec":{},"status":{"healthy":true,"lastHealthyTime":"2018-05-03T13:36:37.729744349Z","bootUUID":"a7edd184-c621-4c0f-90e8-8876e4bb62c4"}},"172_31_222_81":{"uid":"172_31_222_81","generation":1,"changeTime":"2018-05-03T13:37:38.124201337Z","spec":{},"status":{"healthy":true,"lastHealthyTime":"2018-05-03T13:36:37.729745788Z","bootUUID":"ecd1712b-42cc-4027-ab24-55e459df73b2"}},"172_31_57_131":{"uid":"172_31_57_131","generation":1,"changeTime":"2018-05-03T13:37:37.926730349Z","spec":{},"status":{"healthy":true,"lastHealthyTime":"2018-05-03T13:36:37.72974668Z","bootUUID":"ddbf08a8-8f13-40e3-884e-bd0061f5c2a4"}}},"dbs":{"33443894":{"uid":"33443894","generation":2,"changeTime":"2018-05-03T13:37:33.826575925Z","spec":{"keeperUID":"172_31_222_81","requestTimeout":"10s","maxStandbys":20,"additionalWalSenders":5,"additionalReplicationSlots":null,"initMode":"none","pgParameters":{"datestyle":"iso, mdy","default_text_search_config":"pg_catalog.english","dynamic_shared_memory_type":"posix","lc_messages":"en_US.utf8","lc_monetary":"en_US.utf8","lc_numeric":"en_US.utf8","lc_time":"en_US.utf8","log_timezone":"UTC","max_connections":"100","shared_buffers":"128MB","timezone":"UTC","wal_level":"replica"},"pgHBA":null,"role":"standby","followConfig":{"type":"internal","dbuid":"5a363897"},"followers":[],"synchronousStandbys":null,"externalSynchronousStandbys":null},"status":{"healthy":true,"currentGeneration":2,"listenAddress":"172.16.2.126","port":"5432","systemdID":"6523111744617852958","timelineID":12,"xLogPos":2370890112,"timelinesHistory":[{"timelineID":1,"switchPoint":1374014152,"reason":"no recovery target specified"},{"timelineID":2,"switchPoint":1442602280,"reason":"no recovery target specified"},{"timelineID":3,"switchPoint":1469325440,"reason":"no recovery target specified"},{"timelineID":4,"switchPoint":1527769640,"reason":"no recovery target specified"},{"timelineID":5,"switchPoint":1714843664,"reason":"no recovery target specified"},{"timelineID":6,"switchPoint":1778389632,"reason":"no recovery target specified"},{"timelineID":7,"switchPoint":1811943952,"reason":"no recovery target specified"},{"timelineID":8,"switchPoint":1846360416,"reason":"no recovery target specified"},{"timelineID":9,"switchPoint":2046051064,"reason":"no recovery target specified"},{"timelineID":10,"switchPoint":2065613784,"reason":"no recovery target specified"},{"timelineID":11,"switchPoint":2334309352,"reason":"no recovery target specified"}],"pgParameters":{"datestyle":"iso, mdy","default_text_search_config":"pg_catalog.english","dynamic_shared_memory_type":"posix","lc_messages":"en_US.utf8","lc_monetary":"en_US.utf8","lc_numeric":"en_US.utf8","lc_time":"en_US.utf8","log_timezone":"UTC","max_connections":"100","shared_buffers":"128MB","timezone":"UTC","wal_level":"replica"},"synchronousStandbys":[],"olderWalFile":"0000000C000000000000008C"}},"5a363897":{"uid":"5a363897","generation":4,"changeTime":"2018-05-03T13:37:35.728127527Z","spec":{"keeperUID":"172_31_176_43","requestTimeout":"10s","maxStandbys":20,"additionalWalSenders":5,"additionalReplicationSlots":null,"initMode":"none","pgParameters":{"datestyle":"iso, mdy","default_text_search_config":"pg_catalog.english","dynamic_shared_memory_type":"posix","lc_messages":"en_US.utf8","lc_monetary":"en_US.utf8","lc_numeric":"en_US.utf8","lc_time":"en_US.utf8","log_timezone":"UTC","max_connections":"100","shared_buffers":"128MB","timezone":"UTC","wal_level":"replica"},"pgHBA":null,"role":"master","followers":["33443894","b5c554c0"],"synchronousStandbys":null,"externalSynchronousStandbys":null},"status":{"healthy":true,"currentGeneration":4,"listenAddress":"172.16.1.210","port":"5432","systemdID":"6523111744617852958","timelineID":12,"xLogPos":2370890112,"timelinesHistory":[{"timelineID":1,"switchPoint":1374014152,"reason":"no recovery target specified"},{"timelineID":2,"switchPoint":1442602280,"reason":"no recovery target specified"},{"timelineID":3,"switchPoint":1469325440,"reason":"no recovery target specified"},{"timelineID":4,"switchPoint":1527769640,"reason":"no recovery target specified"},{"timelineID":5,"switchPoint":1714843664,"reason":"no recovery target specified"},{"timelineID":6,"switchPoint":1778389632,"reason":"no recovery target specified"},{"timelineID":7,"switchPoint":1811943952,"reason":"no recovery target specified"},{"timelineID":8,"switchPoint":1846360416,"reason":"no recovery target specified"},{"timelineID":9,"switchPoint":2046051064,"reason":"no recovery target specified"},{"timelineID":10,"switchPoint":2065613784,"reason":"no recovery target specified"},{"timelineID":11,"switchPoint":2334309352,"reason":"no recovery target specified"}],"pgParameters":{"datestyle":"iso, mdy","default_text_search_config":"pg_catalog.english","dynamic_shared_memory_type":"posix","lc_messages":"en_US.utf8","lc_monetary":"en_US.utf8","lc_numeric":"en_US.utf8","lc_time":"en_US.utf8","log_timezone":"UTC","max_connections":"100","shared_buffers":"128MB","timezone":"UTC","wal_level":"replica"},"synchronousStandbys":[],"olderWalFile":"0000000B0000000000000089"}},"b5c554c0":{"uid":"b5c554c0","generation":3,"changeTime":"2018-05-03T13:37:37.723192649Z","spec":{"keeperUID":"172_31_57_131","requestTimeout":"10s","maxStandbys":20,"additionalWalSenders":5,"additionalReplicationSlots":null,"initMode":"none","pgParameters":{"datestyle":"iso, mdy","default_text_search_config":"pg_catalog.english","dynamic_shared_memory_type":"posix","lc_messages":"en_US.utf8","lc_monetary":"en_US.utf8","lc_numeric":"en_US.utf8","lc_time":"en_US.utf8","log_timezone":"UTC","max_connections":"100","shared_buffers":"128MB","timezone":"UTC","wal_level":"replica"},"pgHBA":null,"role":"standby","followConfig":{"type":"internal","dbuid":"5a363897"},"followers":[],"synchronousStandbys":null,"externalSynchronousStandbys":null},"status":{"healthy":true,"currentGeneration":3,"listenAddress":"172.16.0.224","port":"5432","systemdID":"6523111744617852958","timelineID":12,"xLogPos":2370890112,"timelinesHistory":[{"timelineID":1,"switchPoint":1374014152,"reason":"no recovery target specified"},{"timelineID":2,"switchPoint":1442602280,"reason":"no recovery target specified"},{"timelineID":3,"switchPoint":1469325440,"reason":"no recovery target specified"},{"timelineID":4,"switchPoint":1527769640,"reason":"no recovery target specified"},{"timelineID":5,"switchPoint":1714843664,"reason":"no recovery target specified"},{"timelineID":6,"switchPoint":1778389632,"reason":"no recovery target specified"},{"timelineID":7,"switchPoint":1811943952,"reason":"no recovery target specified"},{"timelineID":8,"switchPoint":1846360416,"reason":"no recovery target specified"},{"timelineID":9,"switchPoint":2046051064,"reason":"no recovery target specified"},{"timelineID":10,"switchPoint":2065613784,"reason":"no recovery target specified"},{"timelineID":11,"switchPoint":2334309352,"reason":"no recovery target specified"}],"pgParameters":{"datestyle":"iso, mdy","default_text_search_config":"pg_catalog.english","dynamic_shared_memory_type":"posix","lc_messages":"en_US.utf8","lc_monetary":"en_US.utf8","lc_numeric":"en_US.utf8","lc_time":"en_US.utf8","log_timezone":"UTC","max_connections":"100","shared_buffers":"128MB","timezone":"UTC","wal_level":"replica"},"synchronousStandbys":[],"olderWalFile":"0000000B0000000000000086"}}},"proxy":{"generation":71,"changeTime":"2018-05-03T13:18:50.630332616Z","spec":{"masterDbUid":"5a363897","enabledProxies":["4a3ae5bd","d995078b"]},"status":{}}}`
[proxy-log.txt](https://github.com/sorintlab/stolon/files/1971174/proxy-log.txt)
See proxy log in attachment.
Btw 
`kubectl delete po --all -n stolon `
brings cluster up.
Let me know if you need any more information.

**Comment by sergik** [comment] 2018-05-03 15:07
If in this failed state restart only proxies they start writing into logs:
` not proxying to master address since we aren't in the enabled proxies list      {"address": "172.16.1.28:5432"}`

**Comment by sgotti** [comment] 2018-05-03 15:32
@sergik I'm not sure I understand where the issue is. From the last proxy logs looks like some slowness that make them timeout. I see that the keepers and sentinels are correctly working. So the issue is only trying to reach the db from the proxies right?

If so something strange happens when you shutdown and restart the cluster. I'm not able to reproduce it here, shutting down and restarting also after some hours doens't give any problem.

**Comment by sergik** [comment] 2018-05-04 11:49
Added additional tracing into the code and found out the following:
After cluster restart in our case proxy Check method starts work very slow 14-50sec in total.
SetPproxyInfo method(update pod annotation) takes 8-20 sec. At this moment updating same pod using kubectl takes 0 sec. So it stoped after 15 sec timeout as designed.
If at this moment delete all stolon pods,  check starts work for ~100 msec. And everything backs to normal.
For now can not understand what is the reason of such slowness. Will continue investigations. But looks like some kube problem. Client or server not sure for now.

**Comment by sgotti** [comment] 2018-05-04 16:05
@sergik That's really strange. Do you shutdown or suspend the machines hosting the k8s cluster?

**Comment by sergik** [comment] 2018-05-07 08:30
We have staging in aws. With 3 nodes kube cluster based on vm. So by turn off i mean machines stop in aws.

**Comment by sgotti** [comment] 2018-06-05 12:22
@sergik Have you found additional information. I think it's something related to accessing k8s api when restarting the cluster (problem accessing to svc/kubernetes ?)

**Comment by sergik** [comment] 2018-08-15 08:16
It was problem with resource limits. We used quite low limits smth like 0.05 milicores and 16mb memory for proxies and sentinels. And it worked well with etcd and consul implementation but it was a problem with kube. So we just increased limits up to recomended and it started work well.

**Comment by sgotti** [comment] 2018-08-16 14:14
@sergik Glad you figured out the reason. Can we close this?

**Closed** 2018-09-11 09:30 UTC

**Comment by prabhu43** [comment] 2018-10-24 11:46
@sergik What is the recommended resource limits for proxy pods with kube-api store?
