### ISSUE TITLE
stolon not working when istio sidecar injected

### ISSUE THREAD

**Issue by elkh510** [sorintlab/stolon#779] opened 2020-04-13 15:34 UTC
**What happened**:
if istio sidecar injection enabled, unable to connect to stolon:

```
psql --host stolon-proxy -U stolon -d postgres -p 5432
psql: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```
**What you expected to happen**:
normal connecting to stolon
**How to reproduce it (as minimally and precisely as possible)**:
1) deploy istio 1.5.1
2) create namespace (exemple - **stolon**)
3) enable istio-injection (`kubectl label namespace stolon istio-injection=enabled`)
4) deploy stolon by [helm chart ](https://github.com/helm/charts/tree/master/stable/stolon)
5) deploy pod with stolon client and try to connect to stolon server 

**Anything else we need to know?**:
tryed same configuration with [postgres helm chart](https://github.com/helm/charts/tree/master/stable/postgresql) (without stolon) all work as expected

**Environment**:
- Stolon version: v0.16.0
- Stolon running environment (if useful to understand the bug):
- Others:
   istio version: 1.5.1

**Comment by sgotti** [comment] 2020-04-13 15:50
duplicate of #769

**Closed by sgotti** 2020-04-13 15:50 UTC
Labels: bug

**Comment by elkh510** [comment] 2021-01-15 13:38
problem resolves by adding this parameter
`--pg-advertise-port string        postgresql instance port from outside. Use it to expose port different than local port with a PAT networking config`
https://github.com/sorintlab/stolon/blob/master/doc/commands/stolon-keeper.md
