### ISSUE TITLE
Stolon-proxy keep doesn't close the connection with postgres on docker swarm 

### ISSUE THREAD

**Issue by degu89** [sorintlab/stolon#565] opened 2018-09-18 12:57 UTC
Hi, 
I'm having some problem with the number of open connection. 
Stolon is installed in a swarm cluster and it is used by some micro-services. 
The number of connections  are increasing between the keeper and the proxy without an increase of connections between the service and the proxy.

If i check the number of open connection between proxy and one of the microservice, i see 10 connections: 

count | Proto | Recv-Q | Send-Q | Local Address  |         Foreign Address  |       State      
--- | --- |  --------- | ----  | ------------- |---------------- | --------------
01 | tcp |       0   |   0 | 10.0.7.232:35638    |    10.0.7.211:5432  |       ESTABLISHED 
02 | tcp   |     0   |   0 | 10.0.7.232:35642     |   10.0.7.211:5432    |     ESTABLISHED 
03 | tcp   |     0 |     0 | 10.0.7.232:35626    |    10.0.7.211:5432   |      ESTABLISHED 
04 | tcp  |    0    |  0 | 10.0.7.232:35658      |  10.0.7.211:5432     |    ESTABLISHED 
05 | tcp  |      0   |   0 | 10.0.7.232:35654    |    10.0.7.211:5432   |      ESTABLISHED 
06 | tcp  |      0    |  0 | 10.0.7.232:35650    |   10.0.7.211:5432     |    ESTABLISHED 
07 | tcp  |      0    |  0 | 10.0.7.232:35610    |    10.0.7.211:5432    |     ESTABLISHED 
08 | tcp  |      0    |  0 | 10.0.7.232:35634   |     10.0.7.211:5432    |     ESTABLISHED 
09 | tcp  |     0     | 0 | 10.0.7.232:35630   |     10.0.7.211:5432     |    ESTABLISHED 
10 | tcp  |      0    |  0 | 10.0.7.232:35646 |       10.0.7.211:5432    |     ESTABLISHED 

where 10.0.7.232 is the ip of the microservice and 10.0.7.211 the ip of the proxy service
instead the connections on the kepper are many more 

datid	| datname	 | pid	| usesysid |usename	| application_name | client_addr	| client_hostname |	client_port |	backend_start |	xact_start | 	query_start	 |state_change |	wait_event_type	 | wait_event	 | state|	backend_xid |	backend_xmin |	query |	backend_type
--	| --	 | --	| -- |--	| -- | --	| -- |	-- |	-- |	-- | 	-	 |-- |	--	 | --	 | --|	-- |	-- |	-- |	--
18061	| app |	22770	| 18060 |	app |		10.0.3.7 |		58708	| 2018-09-18 08:01:07.310056+00 | 2018-09-18 08:01:07.364066+00	2018-09-18 08:01:07.364117+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	22776	| 18060 |	app |		10.0.3.13 |		42604	| 2018-09-18 08:01:09.561897+00 | 2018-09-18 08:01:09.616763+00	2018-09-18 08:01:09.61681+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	22777	| 18060 |	app |		10.0.3.7 |		58716	| 2018-09-18 08:01:09.669185+00 | 2018-09-18 08:01:09.724004+00	2018-09-18 08:01:09.724054+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	22778	| 18060 |	app |		10.0.3.13 |		42612	| 2018-09-18 08:01:09.777006+00 | 2018-09-18 08:01:09.832493+00	2018-09-18 08:01:09.832553+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	22779	| 18060 |	app |		10.0.3.7 |		58724	| 2018-09-18 08:01:09.885913+00 | 2018-09-18 08:01:09.941143+00	2018-09-18 08:01:09.941178+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	22780	| 18060 |	app |		10.0.3.13 |		42620	| 2018-09-18 08:01:09.993379+00 | 2018-09-18 08:01:10.046447+00	2018-09-18 08:01:10.046494+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	22781	| 18060 |	app |		10.0.3.7 |		58732	| 2018-09-18 08:01:10.099278+00 | 2018-09-18 08:01:10.154176+00	2018-09-18 08:01:10.154211+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	22782	| 18060 |	app |		10.0.3.13 |		42628	| 2018-09-18 08:01:10.206978+00 | 2018-09-18 08:01:10.26186+00	2018-09-18 08:01:10.261909+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	29868	| 18060 |	app |		10.0.3.7 |		34302	| 2018-09-18 08:42:15.846009+00 | 2018-09-18 08:42:15.900506+00	2018-09-18 08:42:15.900556+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	22788	| 18060 |	app |		10.0.3.7 |		58740	| 2018-09-18 08:01:10.314402+00 | 2018-09-18 08:01:10.369469+00	2018-09-18 08:01:10.369519+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	29869	| 18060 |	app |		10.0.3.13 |		46430	| 2018-09-18 08:42:15.95292+00 | 2018-09-18 08:42:16.007825+00	2018-09-18 08:42:16.007859+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	29870	| 18060 |	app |		10.0.3.7 |		34310	| 2018-09-18 08:42:16.061925+00 | 2018-09-18 08:42:16.117039+00	2018-09-18 08:42:16.117092+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	29872	| 18060 |	app |		10.0.3.13 |		46438	| 2018-09-18 08:42:16.169169+00 | 2018-09-18 08:42:16.223479+00	2018-09-18 08:42:16.223527+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	29873	| 18060 |	app |		10.0.3.7 |		34318	| 2018-09-18 08:42:16.275915+00 | 2018-09-18 08:42:16.331176+00	2018-09-18 08:42:16.331227+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	29874	| 18060 |	app |		10.0.3.13 |		46446	| 2018-09-18 08:42:16.383542+00 | 2018-09-18 08:42:16.43803+00	2018-09-18 08:42:16.438077+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	29875	| 18060 |	app |		10.0.3.7 |		34326	| 2018-09-18 08:42:16.49018+00 | 2018-09-18 08:42:16.544571+00	2018-09-18 08:42:16.544644+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	29881	| 18060 |	app |		10.0.3.13 |		46454	| 2018-09-18 08:42:16.596862+00 | 2018-09-18 08:42:16.649969+00	2018-09-18 08:42:16.649999+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	29886	| 18060 |	app |		10.0.3.7 |		34334	| 2018-09-18 08:42:16.702133+00 | 2018-09-18 08:42:16.757125+00	2018-09-18 08:42:16.757183+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	2481	| 18060 |	app |		10.0.3.7 |		37252	| 2018-09-18 09:11:44.859656+00 | 2018-09-18 09:11:44.916394+00	2018-09-18 09:11:44.916452+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	2486	| 18060 |	app |		10.0.3.13 |		49380	| 2018-09-18 09:11:45.34983+00 | 2018-09-18 09:11:45.405645+00	2018-09-18 09:11:45.405692+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	2506	| 18060 |	app |		10.0.3.7 |		37266	| 2018-09-18 09:11:51.504935+00 | 2018-09-18 09:11:51.561021+00	2018-09-18 09:11:51.561075+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	2542	| 18060 |	app |		10.0.3.13 |		49422	| 2018-09-18 09:12:03.380523+00 | 2018-09-18 09:12:03.436888+00	2018-09-18 09:12:03.436946+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	2527	| 18060 |	app |		10.0.3.13 |		49402	| 2018-09-18 09:11:59.894196+00 | 2018-09-18 09:11:59.950707+00	2018-09-18 09:11:59.950765+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	2532	| 18060 |	app |		10.0.3.7 |		37282	| 2018-09-18 09:12:00.718896+00 | 2018-09-18 09:12:00.774922+00	2018-09-18 09:12:00.774973+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	2544	| 18060 |	app |		10.0.3.7 |		37302	| 2018-09-18 09:12:03.615535+00 | 2018-09-18 09:12:03.671564+00	2018-09-18 09:12:03.671633+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	2550	| 18060 |	app |		10.0.3.13 |		49434	| 2018-09-18 09:12:05.720697+00 | 2018-09-18 09:12:05.777246+00	2018-09-18 09:12:05.777304+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	2551	| 18060 |	app |		10.0.3.7 |		37314	| 2018-09-18 09:12:05.831334+00 | 2018-09-18 09:12:05.888001+00	2018-09-18 09:12:05.888052+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	7510	| 18060 |	app |		10.0.3.7 |		39908	| 2018-09-18 09:40:55.629788+00 | 2018-09-18 09:40:55.686231+00	2018-09-18 09:40:55.686285+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	7489	| 18060 |	app |		10.0.3.13 |		52016	| 2018-09-18 09:40:49.465424+00 | 2018-09-18 09:55:20.655949+00	2018-09-18 09:55:20.655981+00	|Client |	ClientRead	 |idle		|	SELECT 1	|client backend
18061	| app |	7511	| 18060 |	app |		10.0.3.13 |		52036	| 2018-09-18 09:40:55.738431+00 | 2018-09-18 09:40:55.793692+00	2018-09-18 09:40:55.793737+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	7512	| 18060 |	app |		10.0.3.7 |		39916	| 2018-09-18 09:40:55.847131+00 | 2018-09-18 09:40:55.902767+00	2018-09-18 09:40:55.902818+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	7513	| 18060 |	app |		10.0.3.13 |		52044	| 2018-09-18 09:40:55.956079+00 | 2018-09-18 09:40:56.010207+00	2018-09-18 09:40:56.010236+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	7519	| 18060 |	app |		10.0.3.13 |		52052	| 2018-09-18 09:40:56.173628+00 | 2018-09-18 09:40:56.229791+00	2018-09-18 09:40:56.229829+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	7518	| 18060 |	app |		10.0.3.7 |		39924	| 2018-09-18 09:40:56.06373+00 | 2018-09-18 09:40:56.119792+00	2018-09-18 09:40:56.119839+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	7520	| 18060 |	app |		10.0.3.7 |		39932	| 2018-09-18 09:40:56.283574+00 | 2018-09-18 09:40:56.340045+00	2018-09-18 09:40:56.340103+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	7522	| 18060 |	app |		10.0.3.7 |		39940	| 2018-09-18 09:40:56.50307+00 | 2018-09-18 09:40:56.55932+00	2018-09-18 09:40:56.559373+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 
18061	| app |	7521	| 18060 |	app		10.0.3.13 |		52060	| 2018-09-18 09:40:56.393881+00		2018-09-18 09:40:56.44933+00	2018-09-18 09:40:56.449359+00	| Client	| ClientRead	| idle	|		SET extra_float_digits = 3 |	client backend 

where 10.0.3.7 and 10.0.3.13 are the ips of the proxy container 

I've also checked with netstat inside the docker and all the connection look established with the keeper
tcp        0      0 213993c462d9:58708      10.0.3.173:postgresql   ESTABLISHED

and  if i check the number of connection between the micro-service and the proxy I see  
(netstat -n --numeric-hosts --numeric-ports|grep 10.0.7.232) 

In the first proxy i've: 

Proto | Recv-Q | Send-Q | Local Address  |         Foreign Address  |       State      
 ---|  --------- | ----  | ------------- |---------------- | --------------
tcp6    |   0    |  0 |  10.0.7.5:5432   |         10.0.7.232:40982        | ESTABLISHED
tcp6    |   0    |  0 | 10.0.7.5:5432   |        10.0.7.232:38320        | ESTABLISHED
tcp6    |   0    |  0 | 10.0.7.5:5432   |        10.0.7.232:46282        | ESTABLISHED
tcp6    |   0    |  0 | 10.0.7.5:5432   |        10.0.7.232:46244        | ESTABLISHED
tcp6    |   0    |  0 |  10.0.7.5:5432   |        10.0.7.232:38328        | ESTABLISHED
tcp6    |   0    |  0 | 10.0.7.5:5432   |        10.0.7.232:43656        | ESTABLISHED
tcp6    |   0    |  0 | 10.0.7.5:5432   |        10.0.7.232:46264        | ESTABLISHED
tcp6    |   0    |  0 | 10.0.7.5:5432   |        10.0.7.232:40956        | ESTABLISHED
tcp6    |   0    |  0 | 10.0.7.5:5432   |        10.0.7.232:40966        | ESTABLISHED
tcp6    |   0    |  0 | 10.0.7.5:5432   |        10.0.7.232:46272        | ESTABLISHED
tcp6    |   0    |  0 | 10.0.7.5:5432   |        10.0.7.232:43632        | ESTABLISHED
tcp6    |   0    |  0 | 10.0.7.5:5432   |        10.0.7.232:38312        | ESTABLISHED
tcp6    |   0    |  0 | 10.0.7.5:5432   |        10.0.7.232:46222        | ESTABLISHED
tcp6    |   0    |  0 | 10.0.7.5:5432   |        10.0.7.232:43616        | ESTABLISHED
tcp6    |   0    |  0 | 10.0.7.5:5432   |        10.0.7.232:43596        | ESTABLISHED
tcp6    |   0    |  0 | 10.0.7.5:5432   |        10.0.7.232:40974        | ESTABLISHED
tcp6    |   0    |  0 | 10.0.7.5:5432   |        10.0.7.232:38302        | ESTABLISHED

for a total of 17 connections
on the second proxy

Proto | Recv-Q | Send-Q | Local Address  |         Foreign Address  |       State      
---|  --------- | ----  | ------------- |---------------- | --------------
tcp6   |    0   |   0 |  10.0.7.4:5432 |          10.0.7.232:43652        | ESTABLISHED
tcp6   |    0   |   0 | 10.0.7.4:5432 |          10.0.7.232:43628        | ESTABLISHED
tcp6   |    0   |   0 | 10.0.7.4:5432 |          10.0.7.232:46268        | ESTABLISHED
tcp6   |    0   |   0 | 10.0.7.4:5432 |          10.0.7.232:48940        | ESTABLISHED
tcp6   |    0   |   0 | 10.0.7.4:5432 |          10.0.7.232:46230        | ESTABLISHED
tcp6   |    0   |   0 | 10.0.7.4:5432 |          10.0.7.232:40986        | ESTABLISHED
tcp6   |    0   |   0 | 10.0.7.4:5432 |          10.0.7.232:40978        | ESTABLISHED
tcp6   |    0   |   0 | 10.0.7.4:5432 |          10.0.7.232:43608        | ESTABLISHED
tcp6   |    0   |   0 | 10.0.7.4:5432 |          10.0.7.232:43662        | ESTABLISHED
tcp6   |    0   |   0 | 10.0.7.4:5432 |          10.0.7.232:40950        | ESTABLISHED
tcp6   |    0   |   0 | 10.0.7.4:5432 |          10.0.7.232:40970        | ESTABLISHED
tcp6   |    0   |   0 | 10.0.7.4:5432 |          10.0.7.232:48958        | ESTABLISHED
tcp6   |    0   |   0 | 10.0.7.4:5432 |          10.0.7.232:40962        | ESTABLISHED
tcp6   |    0   |   0 | 10.0.7.4:5432 |          10.0.7.232:48966        | ESTABLISHED
tcp6   |    0   |   0 | 10.0.7.4:5432 |          10.0.7.232:46278        | ESTABLISHED
tcp6   |    0   |   0 | 10.0.7.4:5432 |          10.0.7.232:48982        | ESTABLISHED
tcp6   |    0   |   0 | 10.0.7.4:5432 |          10.0.7.232:46286        | ESTABLISHED
tcp6   |    0   |   0 | 10.0.7.4:5432 |          10.0.7.232:43592        | ESTABLISHED
tcp6   |    0   |   0 | 10.0.7.4:5432 |          10.0.7.232:46252        | ESTABLISHED
tcp6   |    0   |   0 | 10.0.7.4:5432 |          10.0.7.232:48974        | ESTABLISHED

for a total of 20 connections 

The proxy should drops old connections but they are kept alive. 
I've see that the ticket #323 cover a similar problem, 
Any idea about the problem? 
I'm using the docker sorintlab/stolon:v0.12.0-pg10

**Comment by sgotti** [comment] 2018-09-18 13:36
@degu89 The proxy will close connections when the client connection is closed. As every other TCP server, if the connection isn't marked as closed by the OS (for multiple reasons like not receiving a fin or a reset) it won't know that it's closed. We also implemented TCP keepalive like done by postgres to close dead clients connections (but for your issue, enabling keepalive and shortening its timings will just be a workaround).



I suggest you to investigate the flow between the connections (using netstat or ss) to understand the mapping between client->proxy->keeper and see where an already closed connection between the client and the proxy is yet opened between the proxy and the keeper. Looks like your environment has a lot of snat rules so it could be difficult and probably your issue is related to how docker swarm handles connection between the containers.

So I don't think there's a proxy bug (or it should be easy reproducible also in a standard environment).

**Comment by sgotti** [comment] 2018-10-05 12:46
@degu89 Do you have some updates on this?

**Comment by sgotti** [comment] 2018-10-12 13:43
Closing, please ask to reopen when providing the required info.

**Closed by sgotti** 2018-10-12 13:43 UTC
Labels: needs more info

**Comment by johannesboon** [comment] 2019-04-02 12:08
This is most likely caused by this Docker Swarm issue:

https://success.docker.com/article/ipvs-connection-timeout-issue

Try lowering the keepalive time on Linux like this:

sysctl -w net.ipv4.tcp_keepalive_time=600
