### ISSUE TITLE
Load-Balancing Support

### ISSUE THREAD

**Issue by testark** [sorintlab/stolon#237] opened 2017-01-24 17:31 UTC
We're currently thinking about using `stolon` to deploy a HA cluster inside Kubernetes, but we'd also like to take advantage of hot-standby replicas to serve read-only queries. I have two questions here:

1) Is there some kind of load-balancing support built into `stolon`?
2) In case there's not, and assuming I can easily do load-balancing "client-side", is there a way to get a service to point to the current master and another service pointing to the set of read-only replicas?

**Comment by testark** [comment] 2017-01-27 09:01
@sgotti can you please shed some light?

**Comment by sgotti** [comment] 2017-01-27 19:22
@testark  looks the same as #132 

Basically the primary focus is on postgres HA. As an improvement the proxy could be enhanced to also balance RO connections to the standbys but there're various things to consider (for example which replicas should be used: only the replicas below a defined lag, is it ok to close connections if a replica stops syncing etc...) and currently doing this is not a priority but we'll be happy to review PRs.

As a custom solution you can read the cluster data and implement your own load balancing.

**Comment by sgotti** [comment] 2017-04-24 09:58
@testark I'll close this as a duplicate of #132. We'll happily accept and review PRs.

**Closed by sgotti** 2017-04-24 09:58 UTC
Labels: duplicate
