### ISSUE TITLE
Question:The master postgresql has started, but the slave postgres can't start because of pg_stop_backup

### ISSUE THREAD

**Issue by abcxiaod** [sorintlab/stolon#349] opened 2017-09-04 08:13 UTC
the keep log on the slave postgres:
[E] 2017-09-04T07:07:29Z keeper.go:857: db failed to initialize or resync
[I] 2017-09-04T07:07:29Z keeper.go:907: current db UID different than cluster data db UID db= cdDB=e6cd8731
[I] 2017-09-04T07:07:29Z keeper.go:1052: resyncing the database cluster
[I] 2017-09-04T07:07:29Z keeper.go:1081: database cluster not initialized
[I] 2017-09-04T07:07:29Z postgresql.go:650: running pg_basebackup
NOTICE:  pg_stop_backup cleanup done, waiting for required WAL segments to be archived
..........
WARNING:  pg_stop_backup still waiting for all required WAL segments to be archived (1920 seconds elapsed)
HINT:  Check that your archive_command is executing properly.  pg_stop_backup can be canceled safely, but the database backup will not be usable without all the WAL segments.

**Comment by sgotti** [comment] 2017-09-04 12:33
@Sharor the mailing list is a better place to ask for support: https://groups.google.com/forum/#!forum/stolon (this github issue tracker is for talking about reproducible issues or feature requests).

Looks like you've enabled archive mode and. if so, looks like your archive command isn't correctly working on the primary.

It'll be good if we could disable this check in pg_basebackup since it's not needed for creating a new standby but I'm not sure if this is possible.

**Comment by abcxiaod** [comment] 2017-09-04 13:13
I test the process：
postgres@linux:~> pg_basebackup -h 10.47.223.133 -U replmr -D /pgdata/postgres -P -R
Password: 
22669/22669 kB (100%), 1/1 tablespace
NOTICE:  pg_stop_backup cleanup done, waiting for required WAL segments to be archived



WARNING:  pg_stop_backup still waiting for all required WAL segments to be archived (60 seconds elapsed)
HINT:  Check that your archive_command is executing properly.  pg_stop_backup can be canceled safely, but the database backup will not be usable without all the WAL segments.
WARNING:  pg_stop_backup still waiting for all required WAL segments to be archived (120 seconds elapsed)
HINT:  Check that your archive_command is executing properly.  pg_stop_backup can be canceled safely, but the database backup will not be usable without all the WAL segments.
WARNING:  pg_stop_backup still waiting for all required WAL segments to be archived (240 seconds elapsed)
HINT:  Check that your archive_command is executing properly.  pg_stop_backup can be canceled safely, but the database backup will not be usable without all the WAL segments.
WARNING:  pg_stop_backup still waiting for all required WAL segments to be archived (480 seconds elapsed)
HINT:  Check that your archive_command is executing properly.  pg_stop_backup can be canceled safely, but the database backup will not be usable without all the WAL segments.

but if use -Xs ，it can works：
postgres@linux:/zxdata/pgdata/postgres> pg_basebackup -h 10.47.223.133 -U replmr -D /pgdata/postgres -P -R -Xs
Password: 
22669/22669 kB (100%), 1/1 tablespace

**Comment by abcxiaod** [comment] 2017-09-04 13:33
@sgotti
I test the process：
postgres@linux:~> pg_basebackup -h 10.47.223.133 -U replmr -D /pgdata/postgres -P -R
Password:
22669/22669 kB (100%), 1/1 tablespace
NOTICE: pg_stop_backup cleanup done, waiting for required WAL segments to be archived

WARNING: pg_stop_backup still waiting for all required WAL segments to be archived (60 seconds elapsed)
HINT: Check that your archive_command is executing properly. pg_stop_backup can be canceled safely, but the database backup will not be usable without all the WAL segments.
WARNING: pg_stop_backup still waiting for all required WAL segments to be archived (120 seconds elapsed)
HINT: Check that your archive_command is executing properly. pg_stop_backup can be canceled safely, but the database backup will not be usable without all the WAL segments.
WARNING: pg_stop_backup still waiting for all required WAL segments to be archived (240 seconds elapsed)
HINT: Check that your archive_command is executing properly. pg_stop_backup can be canceled safely, but the database backup will not be usable without all the WAL segments.
WARNING: pg_stop_backup still waiting for all required WAL segments to be archived (480 seconds elapsed)
HINT: Check that your archive_command is executing properly. pg_stop_backup can be canceled safely, but the database backup will not be usable without all the WAL segments.

but if use -Xs ，it can works：
postgres@linux:/zxdata/pgdata/postgres> pg_basebackup -h 10.47.223.133 -U replmr -D /pgdata/postgres -P -R -Xs
Password:
22669/22669 kB (100%), 1/1 tablespace

**Comment by sgotti** [comment] 2017-09-04 14:03
@abcxiaod Thanks. I was under the impression that we were already using -X[f|s] but that's not true so I'll open a PR to fix that.

Can you confirm that your archive command isn't correctly working?

**Comment by sgotti** [comment] 2017-09-04 14:05
Created PR #350

**Comment by abcxiaod** [comment] 2017-09-05 01:11
@sgotti , thanks
My archive command is:
LOGDIR=/pgbak/arch; test ! -d ${LOGDIR} && mkdir -p ${LOGDIR}; test ! -f ${LOGDIR}/%f && cp -p %p ${LOGDIR}/%f


drwxrwxr-x 6 postgres dba 4096 Sep  4 15:02 pgbak
drwxr-xr-x 2 postgres dba 12288 Sep  5 09:04 arch

**Comment by sgotti** [comment] 2017-09-05 07:42
this should be fixed in master since I just merged #350.

@abcxiaod with only the archive command I can't see if it's failing. You should look at the postgres/keeper logs. From the initial logs I'm supposing it's failing. Closing the issue, please reopen if you get the same behavior also with stolon master.

**Closed by sgotti** 2017-09-05 07:42 UTC
